# Generated by Django 2.2 on 2023-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('img', models.ImageField(upload_to='photo')),
                ('dese', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='catge',
            new_name='categ',
        ),
        migrations.RenameField(
            model_name='categ',
            old_name='sleg',
            new_name='slug',
        ),
    ]
