# Generated by Django 2.2 on 2023-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
    ]
