# Generated by Django 2.2 on 2023-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230710_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
