# Generated by Django 2.2 on 2023-08-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230710_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='cartlist',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='product',
            new_name='prodt',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='quantity',
            new_name='quty',
        ),
    ]
